# Generated by Django 3.0.8 on 2020-07-27 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landscaped_backend_app', '0005_auto_20200722_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zip_code',
        ),
        migrations.CreateModel(
            name='CustomersHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_nickname', models.CharField(max_length=255)),
                ('address_1', models.CharField(blank=True, max_length=255)),
                ('address_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('zip_code', models.CharField(blank=True, max_length=15)),
                ('driveway_sqft', models.IntegerField(blank=True)),
                ('driveway_pictures', models.ImageField(upload_to='driveway_pictures')),
                ('yard_sqft', models.IntegerField(blank=True)),
                ('yard_pictures', models.ImageField(upload_to='yard_pictures')),
                ('additional_information', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landscaped_backend_app.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='customers',
            field=models.ManyToManyField(to='landscaped_backend_app.CustomersHome'),
        ),
    ]
